---
- name: Configure Filebeat System Module
  become: true
  template:
    src: filebeat_system.yml.j2
    mode: 0644
    dest: /etc/filebeat/modules.d/system.yml
  notify: restart Filebeat
- name: Configure Filebeat
  become: true
  template:
    src: filebeat.yml.j2
    mode: 0644
    dest: /etc/filebeat/filebeat.yml
  notify: restart Filebeat
- name: Setup filebeat
  become: true
  command:
    cmd: filebeat modules enable system
    chdir: /usr/share/filebeat/bin
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enabled'
- name: Load dashboard
  become: true
  command:
    cmd: filebeat setup
    chdir: /usr/share/filebeat/bin
  register: filebeat_setup
  changed_when: false
  until: filebeat_setup is succeeded